### PR TITLE
Fixed beacon render not working

### LINKED ISSUE #203: [Bug] Beacon range overlay not working correctly
Beacon range overlay only shows range for beacon held in hand. Placed beacons don't show a range.
Tested with only MiniHUD installed.
Game log
https://mclo.gs/F9fRj5z

### PR DESCRIPTION
**Pull request by Cjsah**
The beacon's `primaryPower` is currently not being sent to the client.
As a result, the beacon's range is not rendered correctly.
- Fixed #203

### CODE REVIEW

File: src/main/java/fi/dy/masa/minihud/renderer/BaseBlockRangeOverlay.java [hunk 1]
```diff
@@ -153,18 +153,37 @@ protected boolean fetchAllTargetBlockEntityPositions(ClientLevel world, BlockPos
...
+            BlockPos.MutableBlockPos mutablePos = new BlockPos.MutableBlockPos();
+
+            for (Long pos : removed)
+            {
+                mutablePos.set(pos);
+                this.expireBlockRange(mutablePos.immutable());
+            }
+        }
+
+        return !this.blockPositions.isEmpty();
```
Comment (sakura-ryoko) [inline src/main/java/fi/dy/masa/minihud/renderer/BaseBlockRangeOverlay.java:193]: This part is interesting; but I do have _[PENDING]_ plans to replace this current logic; such as utilizing the WorkerThread to do proper block scans.

File: src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java [hunk 2]
```diff
@@ -60,7 +58,7 @@ protected void updateBlockRange(Level world, BlockPos pos, BeaconBlockEntity be,
         {
             this.positions.remove(pos);
         }
-        else if (level >= 1 && level <= 4 && primary != null)
+        else if (level >= 1 && level <= 4)
```
Comment (sakura-ryoko) [inline src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: These changes may function in your testing; BUT this also creates an issue when the Beacons are enabled/disabled (Such as covering the Beacon with a block); which is why the original `primary != null` check exists.

In order to fix this properly; perhaps this code needs to request the block entity NBT data via `entityDataSync` also; and then make a logical decision based on whether or not this data is accessible.

Yet again; this is an item on my **TODO** list.

Comment (Cjsah) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: However, the level also changes when the beacon is enabled or disabled

Comment (Cjsah) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: I think the beacon's coverage area should be rendered even if no effects have been added yet.

Comment (sakura-ryoko) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: Yeah so; I am just stating that there should be a better way to do this.

Comment (sakura-ryoko) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: I'll ask Masa if that is the intention or not with the Overlay; because there seems to be confusion among users.
If I have to add a "Config" to do this; I will.

Comment (Cjsah) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: That's true.
You're absolutely right.

Comment (sakura-ryoko) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: Masa's response:
```
I'd make it a config if there are several users who prefer different things.
I don't remember anymore how the beacons work, but I think the original implementation uses whatever level the server syncs to the client to know the range. So then if the server doesn't sync anything or syncs like a "disabled" state when it's not on, then I'd say don't render anything if you don't have the info from vanilla to know the range. As in, don't try to calculate the range manually from the beacon base, as then it probably won't work correctly with some mods/modded beacons and whatnot.
```

Comment (sakura-ryoko) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: So needing to add the NBT check and Configuration should be the route; and then the mod makes the final decision based on those two data points; if the intention is to "fix" it.

Comment (sakura-ryoko) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: So if you add a config; call it something like `renderBeaconOverlayAlways` as simple Boolean.

Comment (Cjsah) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: As masa saied, the level is synced from the server to the client.
The ability to check whether a beacon provides potion effects was added in version 1.21.5 (f3da0b6e) .
In previous versions, the beacon’s coverage area was indeed determined solely by its level.

Would it be better to add an option set to false by default to control whether the beacon should sync data from the server?

Comment (sakura-ryoko) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: It would only need to check for the existence of the Primary Status Effect; in addition to the power level; to check if the data is available; or respect the Config option to always show the beacon overlay it if the data is not available.

Comment (sakura-ryoko) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: The `EntitiesDataManager` would only need to report if you are connected to Servux, Backup Mode, or Single Player; and then check for the existence of the `primary_effect` NBT tag.  If the Tag is not present; then the Beacon is disabled; or if Servux, Backup Mode, or Single Player is not present -- then respect the Config option.

Comment (sakura-ryoko) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: Make sense? -- Then the Config Option would determine this behavior depending on whatever the user decides.

Comment (Cjsah) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: But isn’t what we’re discussing exactly whether we need to verify that `primary_effect` is available by default before rendering the border?

In my view, once the server has already sent the beacon level to the client, we should be able to render the border at that point. Verifying whether `primary_effect` is present can be an optional config, so as to send as few requests and network packets as possible to the server.

Comment (Cjsah) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: Right now, we’ve already reached a consensus to add an option that lets players decide whether to verify that they have `primary_effect` before rendering the border; we just have different views on what the default value for this option should be.
Once we’ve arrived at a definitive conclusion, I’ll submit code to follow up and complete this PR as well.

Comment (sakura-ryoko) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: The default should be rendering without checking the `primary_effect` -- and then toggling it will cause it to verify this value.  This way then the default result is roughly the same as the original 1.20.X code.

Sorry, my brain works backwards from my words sometimes.

Comment (sakura-ryoko) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: Anyways I will be starting on the 26.1 code today; but please proceed with 1.21.11.

**Comment by sakura-ryoko** [comment]
Summary:
```
The default should be rendering without checking the primary_effect -- and then toggling it will cause it to verify this value. This way then the default result is roughly the same as the original 1.20.X code.

Sorry, my brain works backwards from my words sometimes.

Anyways I will be starting on the 26.1 code today; but please proceed with 1.21.11.
```

**Comment by sakura-ryoko** [comment]
Just be aware that there were previous "bug reports" concerning that the overlay "doesn't shut off when the beacon is disabled"; but I am also saying that based on what Masa has said as to what the default should be.

**Comment by Cjsah** [comment]
I’m glad we’ve reached a consensus.

**Comment by Cjsah** [comment]
Since we need to check that `primary_effect` exists, we also need to check whether that effect is actually active.

For example, the effect might be set to Level 3, but the beacon itself is only Level 1.

**Comment by sakura-ryoko** [comment]
Okay.  There are a few minor adjustments I'll have to make yet; such as making use of existing tools / the i18n utilization / config comment; but it won't really change logic.  So, you see how the Primary Effect value is effected by whether or not a Beacon is "disabled" by a block while the config is active ?

Also, the i18n needs the config name portion / clarified for what the config's use case is.

**Comment by sakura-ryoko** [comment]
Take a look.  I basically streamlined the data fetching more centralized under the `BaseBlockRangeOverlay`; where this is useful to "double tap" the Block Entity when dealing with server lag, rather than waiting for a second "update" if the data was missed.  Also tested with Servux with and without `entityDataSync` enabled.

**Comment by Cjsah** [comment]
> Okay. There are a few minor adjustments I'll have to make yet; such as making use of existing tools / the i18n utilization / config comment; but it won't really change logic. So, you see how the Primary Effect value is effected by whether or not a Beacon is "disabled" by a block while the config is active ?

When the beacon is blocked, `segments` becomes empty, and `primary_effect` will not change unless the player manually changes the beacon’s Primary Effect.

**Comment by sakura-ryoko** [comment]
Test it out.  It is working as described as the goals in my testing.

**Comment by Cjsah** [comment]
And I received a NPE  crash in singleplayer
```
java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because "pair" is null
	at knot//fi.dy.masa.minihud.data.EntitiesDataManager.tickCache(EntitiesDataManager.java:299)
	at knot//fi.dy.masa.minihud.data.EntitiesDataManager.onClientTick(EntitiesDataManager.java:158)
```

**Comment by sakura-ryoko** [comment]
> And I received a NPE crash in singleplayer
> 
> ```
> java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getLeft()" because "pair" is null
> 	at knot//fi.dy.masa.minihud.data.EntitiesDataManager.tickCache(EntitiesDataManager.java:299)
> 	at knot//fi.dy.masa.minihud.data.EntitiesDataManager.onClientTick(EntitiesDataManager.java:158)
> ```

This must be a Java version thing; as I've seen something like this before in Issues; but where I never have this problem.
It logically doesn't make sense if you Query the KeySet() of a Hashmap; the code would expect that value to be present.

**Comment by Cjsah** [comment]
It was caused by mutablePos.
Because mutablePos can change its coordinates, its hashCode changes as well. As a result, lookups can end up returning null.
I’ve already fixed it.

**Comment by sakura-ryoko** [comment]
OK; but I also added a NULL check for the HashMap, and tuned its constructor; in case other people have the same issue.

**Comment by sakura-ryoko** [comment]
Any other issues?

**Comment by Cjsah** [comment]
Yes—there are still two issues above. I’ve already marked them in the review, but I’m not sure how to quote them in the message.

**Comment by sakura-ryoko** [comment]
> Yes—there are still two issues above. I’ve already marked them in the review, but I’m not sure how to quote them in the message.

Try Copy / Paste.  I do not see any new comments at all in the code that are unresolved on my end.

File: src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java [hunk 3]
```diff
@@ -84,22 +84,26 @@ private boolean checkBeaconActivation(Minecraft mc, Level world, BlockPos pos, I
...
-                    ResourceKey<MobEffect> key = primary.unwrapKey().orElse(null);
+            if (primary != null)
+            {
+                ResourceKey<MobEffect> key = primary.unwrapKey().orElse(null);
 
-                    return key != null && BeaconBlockEntity.BEACON_EFFECTS
+                return key != null && BeaconBlockEntity.BEACON_EFFECTS
                         .stream()
-                        .limit(level)
+//                        .limit(level) ??
```
Comment (Cjsah) [inline src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: This line is used to check whether the beacon’s `current level` is greater than or equal to the level required by the Primary Effect. Otherwise, a player could select a `Level II` beacon effect and then the beacon could drop to `Level I`, `primary_effect` would still exist, but it wouldn’t be able to apply the potion effect to the player.

File: src/main/java/fi/dy/masa/minihud/renderer/BaseBlockRangeOverlay.java [hunk 4]
```diff
@@ -231,26 +240,14 @@ protected void updateBlockRanges(Level world, Vec3 cameraPos, Minecraft mc, Prof
...
-            {
-                CompoundData data = new CompoundData();
-                BlockEntity be = bestWorld.getChunkAt(pos).getBlockEntity(pos);
-                pair = Pair.of(be, be != null ? DataConverterNbt.fromVanillaCompound(be.saveWithFullMetadata(bestWorld.registryAccess())) : data);
-            }
-            else
-            {
-                pair = EntitiesDataManager.getInstance().requestBlockEntity(world, pos);
-            }
+            pair = EntitiesDataManager.getInstance().requestBlockEntity(this.world, pos);
```
Comment (Cjsah) [inline src/main/java/fi/dy/masa/minihud/renderer/BaseBlockRangeOverlay.java:250]: But wouldn’t this end up requesting data for every BlockEntity, even if they don’t need that data?

Comment (sakura-ryoko) [reply src/main/java/fi/dy/masa/minihud/renderer/BaseBlockRangeOverlay.java:250]: Yes, I really don't see a downside to it.  I have additional plans for new Overlays that can also make use of this data; and for an overhaul of this existing system; which also includes the NBT data.  The worst that can happen is it cache's more Beacons in the NBT Cache at once.

File: src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java (hunk 3 above)
Comment (sakura-ryoko) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: If it works for you; when I read the JavaDoc; this param is meant for limiting the number of elements to stream(); so it really didn't make a ton of sense; hence the `??`; but I see what you mean after I went back and checked the Values again.

Comment (Cjsah) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: That’s the idea: each beacon level’s effects are stored as a list, so this method takes the first n elements (i.e., the effect lists for the first n beacon levels), then uses flatMap to merge them into a single list for the check.

File: src/main/java/fi/dy/masa/minihud/renderer/BaseBlockRangeOverlay.java (hunk 4 above)
Comment (sakura-ryoko) [reply src/main/java/fi/dy/masa/minihud/renderer/BaseBlockRangeOverlay.java:250]: Remember; the `BaseBlockRangeOverlay` is only checking for blocks matching the class that extends it; in this case; the Beacon; as opposed to all block entities.  This will only occur for classes that extends it.

File: src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java (hunk 3 above)
Comment (sakura-ryoko) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: So just revert my change there; that's fine.

File: src/main/java/fi/dy/masa/minihud/renderer/BaseBlockRangeOverlay.java (hunk 4 above)
Comment (Cjsah) [reply src/main/java/fi/dy/masa/minihud/renderer/BaseBlockRangeOverlay.java:250]: You’re right—I just noticed it’s only extended by two classes.

File: src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java (hunk 3 above)
Comment (Cjsah) [reply src/main/java/fi/dy/masa/minihud/renderer/OverlayRendererBeaconRange.java]: Okay, no other issues on my end.

**Comment by sakura-ryoko** [comment]
OK I'll let you check it over for a bit before I merge.

**Comment by Cjsah** [comment]
I think the null check in EntitiesDataManager can also be rolled back, since the NPE was only caused by passing the wrong parameter.

**Comment by sakura-ryoko** [comment]
> I think the null check in EntitiesDataManager can also be rolled back, since the NPE was only caused by passing the wrong parameter.

I'd much prefer no crashes.  I've had to add similar checks in Litematica for similar problems when iterating a Hashmap makes no sense to cause an NPE.  I feel that it's better there than not.  If it leaves "Stale" records instead of cleaning them up; it will whenever people change dimensions rather than NPE.  That's good enough for me.

**Comment by Cjsah** [comment]
> I'd much prefer no crashes. I've had to add similar checks in Litematica for similar problems when iterating a Hashmap makes no sense to cause an NPE. I feel that it's better there than not. If it leaves "Stale" records instead of cleaning them up; it will whenever people change dimensions rather than NPE. That's good enough for me.

You are right.

Everything looks fine in my testing on both the client and server.
